Repository BadgerCode/tttdamagelogs, pull requests merged in 2021-07, with the labels that each got.

#58 Use an exclamation for reports awaiting a decision by the reporting player
  lua/damagelogs/client/tabs/rdm_manager.lua
Labels: next-version

#57 Add cr support
  lua/autorun/damagelog_autorun.lua
  lua/damagelogs/client/init.lua
  lua/damagelogs/client/listview.lua
  lua/damagelogs/client/rdm_manager.lua
  lua/damagelogs/server/autoslay.lua
  lua/damagelogs/server/discord.lua
  lua/damagelogs/server/init.lua
  lua/damagelogs/shared/events/fall_damage.lua
  lua/damagelogs/shared/events/kills.lua
  lua/damagelogs/shared/events/suicide.lua
  version.md
Labels: next-version

#62 Replaces non-existent HasTeamRole function for TTT2
  lua/damagelogs/server/autoslay.lua
  lua/damagelogs/shared/events/kills.lua
Labels: next-version

#63 Fixes #41 and made some other improvements
  lua/autorun/damagelog_autorun.lua
  lua/damagelogs/client/tabs/rdm_manager.lua
  lua/damagelogs/config/config.lua
  lua/damagelogs/server/autoslay.lua
  lua/damagelogs/shared/autoslay.lua
  lua/damagelogs/shared/events/fall_damage.lua
  lua/damagelogs/shared/lang/deutsch.lua
Labels: requires-testing

#64 Removes dead function and table
  lua/damagelogs/server/rdm_manager.lua
  lua/damagelogs/shared/lang/deutsch.lua
  lua/damagelogs/shared/lang/english.lua
  lua/damagelogs/shared/lang/french.lua
  lua/damagelogs/shared/lang/polish.lua
  lua/damagelogs/shared/lang/russian.lua
Labels: code-quality

#65 Add Portuguese translation
  lua/damagelogs/shared/lang/brazilian_portuguese.lua
Labels: next-version
